class TeapotStatuses(object):
	NEW_TEAPOT = "NEW_TEAPOT"
	GOOD_TEAPOT = "GOOD_TEAPOT"
	COLD_TEAPOT = "COLD_TEAPOT"
	NO_TEAPOT = "NO_TEAPOT"
	EMPTY_TEAPOT = "EMPTY_TEAPOT"
	NEW_BREWED_TEAPOT = "NEW_BREWED_TEAPOT"
	OLD_BREWED_TEAPOT = "OLD_BREWED_TEAPOT"
	ERROR_STATE = "HTTP_I_AM_A_TEAPOT"